### ISSUE TITLE
Submission links in search results are broken

### ISSUE THREAD

**Issue by s-i-m-s** [adhesivecheese/chearch#2]
submission links all appear as https://adhesivecheese.github.io/chearch/undefined

**Comment by adhesivecheese** [comment]
Patched in [3fdf6d3](https://github.com/adhesivecheese/chearch/commit/3fdf6d3eb28359cc513faf15c9c338ab3f52de4a). `full_link` parameter no longer exists, new parameter with the same value is `url`
