### ISSUE TITLE
Score Filter broken

### ISSUE THREAD

**Issue by 2800X** [adhesivecheese/chearch#3]

**Comment by Esiou** [comment]
Hey @adhesivecheese could you please fix the score filter, TYSM!

**Comment by adhesivecheese** [comment]
Hi there! It looks like the `score` parameter was replaced with `min_score` and `max_score` with the new API. This *should* be a pretty straightforward fix. I've done the changes in the [scorefix](https://github.com/adhesivecheese/chearch/tree/scorefix) branch that *should* take care of things, but I'll need to test before I can push it live. Anybody that feels like testing, please let me know!

**Comment by 2800X** [comment]
@adhesivecheese It's working now, thank you!
